### PR TITLE
fix(pipe): ensure request.headers is present

### LINKED ISSUE #413: context.request.headers is undefined on production
seen on adobe dev site:

```
2019-07-16T00:48:36.918Z       stdout: error: Exception during #13/once:once from /nodejsAction/XXbdNKOd/html.js:257559:
TypeError: Cannot read property 'x-strain' of undefined
    at pre (/nodejsAction/XXbdNKOd/html.js:383905:56)
    at invoker (/nodejsAction/XXbdNKOd/html.js:383826:43)
    at once (/nodejsAction/XXbdNKOd/html.js:383850:14)
    at execFns (/nodejsAction/XXbdNKOd/html.js:109351:17)
    at process._tickCallback (internal/process/next_tick.js:68:7)
2019-07-16T00:48:36.920Z       stdout: debug: context.error -> 500
```

probably from:
```
  logger.info(`strain header: ${context.request.headers['x-strain']}`);
```

/cc @ryanbetts

### PR DESCRIPTION
**Pull request by tripodsan**
fixes #413

### CODE REVIEW

File: src/utils/openwhisk.js [hunk 1]
```diff
@@ -132,8 +132,8 @@ function extractActionContext(params) {
     secrets,
     request: {
       params: disclosed,
-      headers: __ow_headers,
-      method: __ow_method,
+      headers: __ow_headers || {},
```
Comment (trieloff) [inline src/utils/openwhisk.js]: I wonder if it would make sense to populate some default headers, too. e.g. `User-Agent: OpenWhisk`, `X-CDN-Request-Id: manual`
