### PR TITLE
fix(embed): fix external embed service URL construction

### LINKED ISSUE #559: embed creates wrong link in html
for example:
```
https://adobeioruntime.net/api/v1/web/helix/helix-services/embed@v1https://embeds.project-helix.io/jekyll_embed?params=with%20params
```
(missing slash after `@v1`)

also  see https://github.com/adobe/helix-cli/pull/1255/files

### PR DESCRIPTION
**Pull request by trieloff**
the embed service expects the to-be-embedded URL to be passed after a trailing slash. The code did
not add the trailing slash, making it impossible for Adobe I/O Runtime to find the correct action to
execute. This change adds the correct slash again.

fixes https://github.com/adobe/helix-embed/issues/145 fixes #559

### CODE REVIEW

File: src/utils/embed-handler.js [hunk 1]
```diff
@@ -20,7 +20,7 @@ function embed({ EMBED_SERVICE } = {}) {
     const { url } = node;
     const props = {
       // prepend the embed service for absolute URLs
-      src: (URI.parse(url).reference === 'absolute' ? EMBED_SERVICE : '') + url,
+      src: (URI.parse(url).reference === 'absolute' ? `${EMBED_SERVICE}/` : '') + url,
```
Comment (tripodsan) [inline src/utils/embed-handler.js]: this could be more robust and deal with URLs with or without a trailing slash.....
