### PR TITLE
fix(md): relax frontmatter complaining

### LINKED ISSUE #715: data-embed format is considered as invalid frontmatter
Follow up of https://github.com/adobe/helix-pipeline/issues/714#issuecomment-627877564

In local dev and using data embed requires the markdown to look like:

```
Hello world

---
"https://docs.google.com/spreadsheets/d/e/2PACX-1vQ78BeYUV4gFee4bSxjN8u86aV853LGYZlwv1jAUMZFnPn5TnIZteDJwjGr2GNu--zgnpTY1E_KHXcF/pubhtml

Is foo {{foo}}?"
---

```

which is considered as invalid frontmatter by our `remark-matter` (see https://github.com/adobe/helix-pipeline/blob/master/src/html/remark-matter.js#L35-L42) and logged as a warning in dev. This is really confusing:

```
[hlx] warn: Error: Found ambiguous frontmatter block: Block contains valid yaml, but it's data type is function String() { [native code] } instead of Object.Make sure your yaml blocks contain only key-value pairs at the root level!
https://adobe-my.sharepoint.com/personal/acapt_adobe_com/_layouts/15/guestaccess.aspx
1. {{import date}} - {{url}}
    at warn (/Users/acapt/work/dev/helix/playground/hlxsite/.hlx/pages/master/node_modules/@adobe/helix-pipeline/src/html/remark-matter.js:36:17)
    at Of.frontmatter (/Users/acapt/work/dev/helix/playground/hlxsite/.hlx/pages/master/node_modules/@adobe/helix-pipeline/src/html/remark-matter.js:104:14)
    at Of.tokenize [as tokenizeBlock] (/Users/acapt/work/dev/helix/playground/hlxsite/.hlx/pages/master/node_modules/remark-parse/lib/tokenizer.js:62:18)
    at Of.parse (/Users/acapt/work/dev/helix/playground/hlxsite/.hlx/pages/master/node_modules/remark-parse/lib/parse.js:33:20)
    at Function.parse (/Users/acapt/work/dev/helix/playground/hlxsite/.hlx/pages/master/node_modules/unified/index.js:281:45)
    at parseMarkdown (/Users/acapt/work/dev/helix/playground/hlxsite/.hlx/pages/master/node_modules/@adobe/helix-pipeline/src/html/parse-markdown.js:30:6)
    at execFns (/Users/acapt/work/dev/helix/playground/hlxsite/.hlx/pages/master/node_modules/@adobe/helix-pipeline/src/pipeline.js:392:17)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

2 options:
1. remove the warning - debug might be enough
2. find another solution to describe data-embeds.

### LINKED ISSUE #721: Sections trigger ambiguous frontmatter fence error
**Description**
As of late, the pipeline's frontmatter parser complains about empty lines after `---`. Actually, that's exactly how we used to define *Sections* in our documents 😄 - and luckily that still works.

**To Reproduce**
I ran into it while developing on [theblog](https://github.com/adobe/theblog), but you can reproduce it by just adding the following markdown file in your local dev env and requesting it:
```md
# Title

---

Lorem ipsum 1

---

Lorem ipsum 2

---

Lorem ipsum 3
```

**Expected behavior**
No complaints when `---` is followed by an empty line

**Actual behavior**
```
Error: Found ambiguous frontmatter fence: Block contains empty line! Make sure your mid-document YAML blocks contain no empty lines and your horizontal rules have an empty line before AND after them. Lorem ipsum 1
```

**Version:**
helix-pipeline 7.1.3

### PR DESCRIPTION
**Pull request by tripodsan**
fixes #721, fixes #715

### CODE REVIEW

File: src/html/remark-matter.js [hunk 1]
```diff
@@ -41,75 +40,94 @@ function createTokenizer(opts) {
...
-    }
+    const src = match[2];
 
     // reject ambiguous yaml
-    if (/^\s*:/m.test(src)) {
-      return warn(
-        'Found ambiguous frontmatter fence: Block contains yaml key starting with \':\'.'
+    if (/^\s*[^a-zA-Z"{\s-]/m.test(src)) {
+      return info(
+        'Found ambiguous frontmatter fence: Block contains yaml key not starting a letter. '
```
Comment (trieloff) [inline src/html/remark-matter.js:75]:
```suggestion
        'Found ambiguous frontmatter fence: Block contains yaml key not starting with a letter. '
```

**Comment by tripodsan** [comment]
@trieloff  @kptdobe regarding:
https://lgtm.com/projects/g/adobe/helix-pipeline/rev/pr-4e5d67cc425aad447df9bd461243f126e9fcd39a

should we create a canonical form of the markdown by converting it to LF (before parsing)?

**Comment by tripodsan** [comment]
> should we create a canonical form of the markdown by converting it to LF (before parsing)?

I added the conversion....
