### PR TITLE
fix(openwhisk.js): fix bottomless recursion issue

### LINKED ISSUE #543: Winston logger compatibility seems to be broken
It is no longer possible to run `helix_demo` project as described [here](https://www.project-helix.io/). I get these errors when running `hlx up`:
```
[hlx] error: Exception during #00/use:parseMarkdown from /Users/albina/Desktop/helix/hello_helix/.hlx/build/node_modules/@adobe/helix-pipeline/src/defaults/html.pipe.js:63:
RangeError: Maximum call stack size exceeded
    at DerivedLogger.(anonymous function) (/Users/albina/.nvm/versions/node/v10.16.3/lib/node_modules/@adobe/helix-cli/node_modules/winston/lib/winston/create-logger.js:95:19)
    at DerivedLogger.__ow_logger.log.msg [as log] (/Users/albina/Desktop/helix/hello_helix/.hlx/build/node_modules/@adobe/helix-pipeline/src/utils/openwhisk.js:133:60)
    at DerivedLogger.(anonymous function) (/Users/albina/.nvm/versions/node/v10.16.3/lib/node_modules/@adobe/helix-cli/node_modules/winston/lib/winston/create-logger.js:95:19)
    at DerivedLogger.__ow_logger.log.msg [as log] (/Users/albina/Desktop/helix/hello_helix/.hlx/build/node_modules/@adobe/helix-pipeline/src/utils/openwhisk.js:133:60)
    at DerivedLogger.(anonymous function) (/Users/albina/.nvm/versions/node/v10.16.3/lib/node_modules/@adobe/helix-cli/node_modules/winston/lib/winston/create-logger.js:95:19)
    at DerivedLogger.__ow_logger.log.msg [as log] (/Users/albina/Desktop/helix/hello_helix/.hlx/build/node_modules/@adobe/helix-pipeline/src/utils/openwhisk.js:133:60)
    at DerivedLogger.(anonymous function) (/Users/albina/.nvm/versions/node/v10.16.3/lib/node_modules/@adobe/helix-cli/node_modules/winston/lib/winston/create-logger.js:95:19)
    at DerivedLogger.__ow_logger.log.msg [as log] (/Users/albina/Desktop/helix/hello_helix/.hlx/build/node_modules/@adobe/helix-pipeline/src/utils/openwhisk.js:133:60)
    at DerivedLogger.(anonymous function) (/Users/albina/.nvm/versions/node/v10.16.3/lib/node_modules/@adobe/helix-cli/node_modules/winston/lib/winston/create-logger.js:95:19)
    at DerivedLogger.__ow_logger.log.msg [as log] (/Users/albina/Desktop/helix/hello_helix/.hlx/build/node_modules/@adobe/helix-pipeline/src/utils/openwhisk.js:133:60)
```

Looks like https://github.com/adobe/helix-pipeline/commit/4f3138171c95178b756a3cc072ebcf747da19069#diff-ebc7672f50d3fcf4ce1716569cc278bfL133-L138 is the reason for that.

### PR DESCRIPTION
**Pull request by MarquiseRosier**
winston logger is compatible through logger.log already

fix #543

### CODE REVIEW

**Comment by MarquiseRosier** [comment]
removed those lines of code, because logger.log already works for as needed for Winston.

File: src/utils/openwhisk.js [hunk 1]
```diff
@@ -128,11 +128,6 @@ function extractActionContext(params) {
   // extract content (will be added to context)
   delete disclosed.content;
 
-  // keep logger backward compatible with winston logger
-  if (__ow_logger) {
```
Comment (kptdobe) [inline src/utils/openwhisk.js]: I kind of remember this line is mandatory and I am pretty sure that removing it will introduce a regression somewhere (@tripodsan did not add it just for fun ;) ). Did you test this new pipeline with the simulator AND in "production" ?

Based on your comment https://github.com/adobe/helix-cli/issues/1240#issuecomment-564251287, I think that changing the `if` should be enough to fix the issue: 

```
if (__ow_logger && !__ow_logger.log) {
```

to not override an existing `log` function (or something like that ;) )

Comment (MarquiseRosier) [reply src/utils/openwhisk.js]: ^@kptdobe  yes, hmmm. I searched through Winston's codes history to see when it was ever without a .log function, and didn't find anything where it was different and wouldn't result in the same issue. This might be a powerful lesson in nothing is as it seems :D 

I tested with pipeline installed in helix-cli node_modules during hlx up!

**Comment by kptdobe** [comment]
Together with https://github.com/adobe/helix-cli/pull/1243, I managed to run the helix-cli tests with the current PR and they all pass. So I think we should merge.

**Comment by kptdobe** [comment]
I forced merged the PR to be able to unlock the situation (our cli has been broken for more than a week). We can still update later if needed.

**Comment by MarquiseRosier** [comment]
Perfect! Thanks for this merge @kptdobe

File: src/utils/openwhisk.js (hunk 1 above)
Comment (tripodsan) [reply src/utils/openwhisk.js]: the problem is, that winston logger has a `log(level, msg)` method, but helix-log implements `log(msg)` only (following console.log semantics). so while this still "works", it will output a wrong log-message.

but let's keep it this way, as we are going to refactor the logging anyways in the next days.

Comment (MarquiseRosier) [reply src/utils/openwhisk.js]: ahh great point, I didn't see this. Thank you.
